"""add course status

Revision ID: 1252d54a689b
Revises: 247598456566
Create Date: 2026-07-24 22:17:25.839265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1252d54a689b'
down_revision: Union[str, Sequence[str], None] = '247598456566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "courses",
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            server_default="draft"
        )
    )

    op.alter_column(
        "courses",
        "status",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###
